[package]
name = "holochain_test_bin"
version = "0.1.0"
authors = ["neonphog <neonphog@gmail.com>"]

[dependencies]
holochain_core = { path = "../core" }
holochain_core_api = { path = "../core_api" }
holochain_core_types = { path = "../core_types" }
